name: Merge
description: Merge
inputs:
  lock_branch:
    description: |
      A GitHub branch to lock
    required: true

  pr_number:
    description: |
      Pull Request Number to merge
    required: true

  github_token:
    description: |
      GitHub Access Token
      contents:write - Push commits
      pull-requests:write - Create pull request comments and labels
    required: false
    default: ${{ github.token }}

  target:
    description: |
      A target to lock
    required: false
runs:
  using: composite
  steps:
    - name: Check lock
      id: check-lock
      uses: ./actions/check-lock
      with:
        github_token: ${{inputs.github_token}}
        lock_branch: ${{inputs.lock_branch}}

    - name: The target has already been locked
      shell: bash
      if: steps.check-lock.outputs.is_locked == 'true'
      run: |
        echo "::error::The target has already been locked"
        github-comment post -k already-locked -var "target:$TARGET" -var "commit_sha:${COMMIT_SHA}"
        exit 1
      env:
        GITHUB_TOKEN: ${{inputs.github_token}}
        COMMIT_SHA: ${{steps.check-lock.outputs.commit_sha}}

    - name: Lock
      uses: ./actions/lock
      with:
        github_token: ${{inputs.github_token}}
        lock_branch: ${{inputs.lock_branch}}

    - name: Merge
      id: merge
      shell: bash
      run: |
        github-comment exec -- gh pr merge "$PR_NUMBER" -s
      env:
        PR_NUMBER: ${{inputs.pr_number}}
        GITHUB_TOKEN: ${{inputs.github_token}}

    - name: Unlock if it failed to merge
      if: steps.merge.outcome != 'success'
      uses: ./actions/unlock
      with:
        github_token: ${{inputs.github_token}}
        lock_branch: ${{inputs.lock_branch}}
        target: ${{inputs.target}}
