---
name: Merge
on:
  issue_comment:
    types:
      - created
jobs:
  merge:
    runs-on: ubuntu-latest
    if: |
      github.event.issue.pull_request && github.event.comment.body == '/merge'
    permissions: {}
    env:
      TARGET: foo
      LOCK_BRANCH: lock/foo
      GH_COMMENT_PR_NUMBER: ${{github.event.issue.number}}
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - id: token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        with:
          app_id: ${{secrets.APP_ID}}
          private_key: ${{secrets.APP_PRIVATE_KEY}}
          permissions: >-
            {
              "contents": "write",
              "pull_requests": "write"
            }
          repositories: >-
            [
              "${{github.event.repository.name}}"
            ]

      - uses: aquaproj/aqua-installer@v2.3.0
        with:
          aqua_version: v2.23.2
        env:
          GITHUB_TOKEN: ${{steps.token.outputs.token}}

      - name: Merge
        uses: ./actions/merge
        with:
          github_token: ${{steps.token.outputs.token}}
          target: ${{env.TARGET}}
          lock_branch: ${{env.LOCK_BRANCH}}
          pr_number: ${{github.event.issue.number}}
